# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyboardKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KeyboardKitExample

  target 'KeyboardKitExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyboardKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KeyboardKitExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KeyboardKitExample-tvOS

  target 'KeyboardKitExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
